stages:
  - .pre
  - test
  - build
  - release

variables:
  # Change pip's cache directory to be inside the project directory since we can
  # only cache local items.
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt

  BASE_CI_IMAGE_DOCKER_REGISTRY: docker.ops.iszn.cz
  BASE_CI_IMAGE_NAMESPACE: cdn/ci

include:
  - project: cdnko/tools/ci-scripts
    ref: master
    file:
      ### pre: poetry-bump-dev-version
      - /templates/v1/pre/poetry-bump-dev-version.yml
      ### test: pytest
      - /templates/v1/tests/poetry-tox-pytest.yml
      ### build: poetry-build
      - /templates/v1/build/poetry.yml
      ### release: Bump version via commitizen and push tag to git
      - /templates/v1/release/poetry-cz-bump-tag.yml
      ### release to https://repo.ops.iszn.cz/pypi
      - /templates/v1/release/poetry-pypi-szn.yml
