name: Merge master into release branch to trigger release

on:
  pull_request:
    types:
      - closed

jobs:
  sync-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge development -> staging
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: release
          github_token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
